development:
  adapter: postgresql
  database: basic_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: basic_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: basic_production
  pool: 5
  timeout: 5000